Repository MieuxVoter/majority-judgment-offline-urn-android, pull requests merged in 2025-03, with the labels that each got.

#10 Show latest added proposal to the top of the list
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/logic/PollSetupViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
Labels: enhancement

#11 Randomize proposals
  app/src/main/java/com/illiouchine/jm/logic/PollVotingViewModel.kt
  app/src/main/java/com/illiouchine/jm/model/Ballot.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/PollSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/BallotSummaryScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/theme/Color.kt
  app/src/main/java/com/illiouchine/jm/ui/theme/Theme.kt
Labels: enhancement

#5 Instrumentation testing
  app/build.gradle.kts
  app/src/androidTest/assets/features/01-onboarding.feature
  app/src/androidTest/assets/features/02-making-a-poll.feature
  app/src/androidTest/java/com/illiouchine/jm/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/illiouchine/jm/README.md
  app/src/androidTest/java/com/illiouchine/jm/test/ActivityScenarioHolder.kt
  app/src/androidTest/java/com/illiouchine/jm/test/ComposeRuleHolder.kt
  app/src/androidTest/java/com/illiouchine/jm/test/CucumberRunner.kt
  app/src/androidTest/java/com/illiouchine/jm/test/CucumberSteps.kt
  app/src/androidTest/java/com/illiouchine/jm/test/DummySteps.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/BaseInstrumentedTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleActivityRuleTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleComposeRuleTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/README.md
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
Labels: enhancement

#14 Ask for confirmation before deleting a poll
  app/src/main/java/com/illiouchine/jm/ui/composable/PollDeletionConfirmationDialog.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/PollSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#16 Add a fab button displayed when finish is out of screen
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/utils/Displayed.kt
Labels: enhancement

#24 Adapt to low density devices (use sp not em)
  app/src/main/java/com/illiouchine/jm/ui/composable/GradeSelectionButton.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/GradeSelectionList.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/JudgmentSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/PollSubject.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/PollSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/BallotSummaryScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/SettingsScreen.kt
Labels: bug

#15 More details on the result screen
  README.md
  app/src/main/java/com/illiouchine/jm/ui/composable/BallotCountRow.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/BallotSummaryScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
Labels: enhancement

#25 Translate the verb 'is' on the summary screen
  app/src/main/java/com/illiouchine/jm/ui/composable/JudgmentSummary.kt
Labels: enhancement

#29 Configure issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#30 Improved about screen
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/IconTextButton.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  metadata/en-US/changelogs/6.txt
Labels: documentation

#32 typos in fastlane
  metadata/en-US/full_description.txt
  metadata/en-US/short_description.txt
Labels: documentation

#33 Review the french fastlane metadata (SEO)
  metadata/fr-FR/full_description.txt
  metadata/fr-FR/short_description.txt
Labels: documentation

#38 Huge Refacto & Feat suggest poll subject and proposal name
  app/build.gradle.kts
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/MajorityUrnApplication.kt
  app/src/main/java/com/illiouchine/jm/Screens.kt
  app/src/main/java/com/illiouchine/jm/logic/HomeViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/PollResultViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/PollSetupViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/PollVotingViewModel.kt
  app/src/main/java/com/illiouchine/jm/model/Ballot.kt
  app/src/main/java/com/illiouchine/jm/model/Grade.kt
  app/src/main/java/com/illiouchine/jm/model/Grading.kt
  app/src/main/java/com/illiouchine/jm/model/Judgment.kt
  app/src/main/java/com/illiouchine/jm/model/Poll.kt
  app/src/main/java/com/illiouchine/jm/model/PollConfig.kt
  app/src/main/java/com/illiouchine/jm/ui/Navigator.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/MjuBottomBar.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/MjuSnackbar.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/ProposalRow.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/ProposalSelectionRow.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/ScreenTitle.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/SubjectSelectionRow.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/SuggestionPopup.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/ThemedHorizontalDivider.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/SettingsScreen.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#41 fix: low density confirmation dialog
  app/src/main/java/com/illiouchine/jm/ui/composable/PollDeletionConfirmationDialog.kt
Labels: bug

#39 Add a link in About to the online webapp
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/res/values/strings.xml
Labels: documentation

#43 Update the screenshots
  README.md
  metadata/en-US/images/phoneScreenshots/1.png
  metadata/en-US/images/phoneScreenshots/2.png
  metadata/en-US/images/phoneScreenshots/3.png
  metadata/en-US/images/phoneScreenshots/4.png
Labels: documentation

#45 Automatically pin screen (opt-in)
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/data/SharedPrefsHelper.kt
  app/src/main/java/com/illiouchine/jm/logic/SettingsViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/SettingsScreen.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  metadata/en-US/changelogs/6.txt
Labels: enhancement, ux

#44 Review fastlane metadata, add en-GB
  README.md
  metadata/en-GB/full_description.txt
  metadata/en-GB/short_description.txt
  metadata/en-GB/title.txt
  metadata/en-US/changelogs/6.txt
  metadata/en-US/full_description.txt
  metadata/en-US/images/icon.png
  metadata/en-US/short_description.txt
  metadata/fr-FR/short_description.txt
Labels: documentation

#47 Readable suggestion colors and caret repositioning at the end
  app/src/main/java/com/illiouchine/jm/ui/composable/ProposalSelectionRow.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/SuggestionPopup.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/theme/Color.kt
  app/src/main/java/com/illiouchine/jm/ui/theme/Theme.kt
Labels: enhancement

#51 Fix navigation
  app/build.gradle.kts
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/MajorityUrnApplication.kt
  app/src/main/java/com/illiouchine/jm/data/BDDPollDataSource.kt
  app/src/main/java/com/illiouchine/jm/data/InMemoryPollDataSource.kt
  app/src/main/java/com/illiouchine/jm/data/PollDataSource.kt
  app/src/main/java/com/illiouchine/jm/data/SharedPrefsHelper.kt
  app/src/main/java/com/illiouchine/jm/data/SqlitePollDataSource.kt
  app/src/main/java/com/illiouchine/jm/data/room/PollDao.kt
  app/src/main/java/com/illiouchine/jm/data/room/PollDataBase.kt
  app/src/main/java/com/illiouchine/jm/data/room/RoomMapper.kt
  app/src/main/java/com/illiouchine/jm/logic/HomeViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/PollSetupViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/PollVotingViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/SettingsViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/Navigator.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/LinearMeritProfileCanvas.kt
  gradle/libs.versions.toml
  metadata/en-GB/short_description.txt
  metadata/en-US/short_description.txt
Labels: bug

#57 Explain results
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/logic/PollResultViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/PollVotingViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/LinearMeritProfileCanvas.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/utils/Curves.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: documentation

#58 Fixes for explanations and small screens
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/logic/PollResultViewModel.kt
  app/src/main/java/com/illiouchine/jm/service/DuelAnalyzer.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/LinearMeritProfileCanvas.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  metadata/en-US/changelogs/6.txt
  tools/collect_authors.sh
Labels: bug

#59 Optimize build size
  app/build.gradle.kts
  metadata/en-US/changelogs/6.txt
Labels: enhancement

#61 Add two safeguards against inspecting empty polls
  app/src/main/java/com/illiouchine/jm/ui/composable/PollSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
Labels: bug

#65 fix: onboarding's Finish button was unresponsive
  app/src/androidTest/assets/features/01-onboarding.feature
  app/src/androidTest/assets/features/02-making-a-poll.feature
  app/src/androidTest/java/com/illiouchine/jm/test/CucumberSteps.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleActivityRuleTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleComposeRuleTest.kt
  app/src/main/java/com/illiouchine/jm/logic/HomeViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
Labels: bug

#67 fix: app pinning
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
Labels: bug

#68 Polish
  app/src/androidTest/assets/features/02-making-a-poll.feature
  app/src/androidTest/java/com/illiouchine/jm/test/CucumberSteps.kt
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/service/DuelAnalyzer.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/GradeSelectionList.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
Labels: enhancement

#70 Italic grade names in explanations
  app/src/main/java/com/illiouchine/jm/logic/PollResultViewModel.kt
  app/src/main/java/com/illiouchine/jm/service/DuelAnalyzer.kt
  app/src/main/java/com/illiouchine/jm/service/TextStylist.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#76 fix(i18n): translate the forgotten placeholders
  app/src/main/java/com/illiouchine/jm/ui/composable/ProposalSelectionRow.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/SubjectSelectionRow.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: translation

#78 fix: fixed issue when doing slow swipe back on onboarding screen
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
Labels: bug

#92 Fix keyboard focus on older Androids
  app/build.gradle.kts
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/ProposalSelectionRow.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/SubjectSelectionRow.kt
  metadata/README.md
  metadata/en-US/changelogs/7.txt
Labels: critical

#94 Fix issue with default grading and use 5 grades as default
  app/src/main/java/com/illiouchine/jm/data/SharedPrefsHelper.kt
  app/src/main/java/com/illiouchine/jm/data/SqlitePollDataSource.kt
  app/src/main/java/com/illiouchine/jm/logic/Constants.kt
  app/src/main/java/com/illiouchine/jm/logic/PollSetupViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/SettingsViewModel.kt
  app/src/main/java/com/illiouchine/jm/model/Grading.kt
  app/src/main/java/com/illiouchine/jm/model/PollConfig.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/GradeSelectionList.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/GradingSelectionRow.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/BallotSummaryScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
Labels: bug

#95 Fix losing inputs of poll setup on screen rotation
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/logic/PollSetupViewModel.kt
  app/src/main/java/com/illiouchine/jm/model/Grade.kt
  app/src/main/java/com/illiouchine/jm/model/Grading.kt
  app/src/main/java/com/illiouchine/jm/ui/Navigator.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollSetupScreen.kt
Labels: bug, critical

#81 Add a Loader Composable
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/ui/Navigator.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/loading/Loader.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/loading/Spirograph.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/loading/SpirographMenu.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/LoaderScreen.kt
Labels: ux, juice
