Repository MieuxVoter/majority-judgment-offline-urn-android, pull requests merged in 2025-04, with the labels that each got.

#109 Fix weblate MRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/android_build.yml
  .github/workflows/android_check.yml
Labels: bug

#105 Translations update from Hosted Weblate
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-tr/strings.xml
Labels: translation

#102 Feat: Moving Onbording screen to its appropriate screen.
  .DS_Store
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/MajorityUrnApplication.kt
  app/src/main/java/com/illiouchine/jm/logic/HomeViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/OnBoardingViewModel.kt
  app/src/main/java/com/illiouchine/jm/logic/SettingsViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/Navigator.kt
  app/src/main/java/com/illiouchine/jm/ui/composable/loading/SpirographMenu.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/SettingsScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, ux

#115 Correctly compose long proposal names on the ballot confirmation screen
  app/src/main/java/com/illiouchine/jm/ui/composable/JudgmentSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/BallotSummaryScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  metadata/en-US/changelogs/9.txt
Labels: bug

#116 Allow toggling switches in settings by tapping their label
  app/src/main/java/com/illiouchine/jm/ui/screen/SettingsScreen.kt
Labels: enhancement, ux

#120 Take care of the last detekt warnings
  app/build.gradle.kts
  app/src/androidTest/java/com/illiouchine/jm/test/ActivityScenarioHolder.kt
  app/src/androidTest/java/com/illiouchine/jm/test/CucumberRunner.kt
  app/src/androidTest/java/com/illiouchine/jm/test/DummySteps.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/BaseInstrumentedTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleActivityRuleTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleComposeRuleTest.kt
  app/src/androidTest/java/com/illiouchine/jm/unused/ExampleInstrumentedTest.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollVotingScreen.kt
  build.gradle.kts
  detekt.yml
  settings.gradle.kts
Labels: automated test

#121 Translations update from Hosted Weblate
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  metadata/en-GB/changelogs/5.txt
  metadata/en-GB/changelogs/6.txt
  metadata/en-GB/changelogs/7.txt
  metadata/en-GB/changelogs/8.txt
  metadata/en-GB/changelogs/9.txt
  metadata/en-GB/privacy_policy.txt
  metadata/en-GB/short_description.txt
  metadata/en-GB/title.txt
Labels: translation

#123 Restore the compose previews of the results screen
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
  app/src/main/java/com/illiouchine/jm/data/InMemoryPollDataSource.kt
  app/src/main/java/com/illiouchine/jm/logic/PollResultViewModel.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/OnBoardingScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/PollResultScreen.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: cleanup

#128 Build and sign an AAB for Google Play
  .github/workflows/android_build.yml
  .gitignore
  README.md
  app/build.gradle.kts
  metadata/en-US/changelogs/10.txt
  metadata/en-US/changelogs/11.txt
  metadata/en-US/changelogs/9.txt
  metadata/en-US/privacy_policy.txt
Labels: publication

#131 Style padding by kze
  app/src/main/java/com/illiouchine/jm/ui/composable/PollSummary.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/HomeScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/screen/SettingsScreen.kt
Labels: enhancement, cleanup

#129 Add constant spacing in theme and an example of use in AboutScreen
  app/src/main/java/com/illiouchine/jm/ui/screen/AboutScreen.kt
  app/src/main/java/com/illiouchine/jm/ui/theme/Spacing.kt
  app/src/main/java/com/illiouchine/jm/ui/theme/Theme.kt
Labels: cleanup

#132 Translations update from Hosted Weblate
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  metadata/en-GB/changelogs/10.txt
  metadata/en-GB/changelogs/11.txt
  metadata/en-GB/changelogs/9.txt
  metadata/en-GB/privacy_policy.txt
  metadata/fr-FR/changelogs/10.txt
  metadata/fr-FR/changelogs/11.txt
  metadata/fr-FR/changelogs/5.txt
  metadata/fr-FR/changelogs/9.txt
  metadata/fr-FR/privacy_policy.txt
Labels: translation

#134 Remove DS_Store
  .DS_Store
  .gitignore
Labels: cleanup

#136 Add 5 urgency grades
  app/src/main/java/com/illiouchine/jm/model/Grade.kt
  app/src/main/java/com/illiouchine/jm/model/Grading.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#135 Setup database migrations
  app/schemas/com.illiouchine.jm.data.room.PollDataBase/1.json
  app/schemas/com.illiouchine.jm.data.room.PollDataBase/2.json
  app/src/main/java/com/illiouchine/jm/data/SqlitePollDataSource.kt
  app/src/main/java/com/illiouchine/jm/data/room/PollDataBase.kt
  app/src/main/java/com/illiouchine/jm/data/room/RoomMapper.kt
  app/src/main/java/com/illiouchine/jm/data/room/entity/PollEntity.kt
Labels: cleanup

#137 Translations update from Hosted Weblate
  app/src/main/res/values-fr/strings.xml
Labels: translation

#139 Prevent a screen flicker during navigation on dark mode
  app/src/main/java/com/illiouchine/jm/MainActivity.kt
Labels: bug
